---
version: 3

build_arg_defaults:
  # EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'
  
ansible_config: '../ansible.cfg'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt

images:
  base_image:
    name: quay.io/rockylinux/rockylinux:9

additional_build_steps:
  prepend_base: |
    RUN pip3 install --upgrade pip setuptools
  # append: |
  #   LABEL quay.expires-after="45d"