---
version: 3
images:
  base_image:
    name: quay.io/rockylinux/rockylinux:9

build_arg_defaults:
  # EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'
  
additional_build_files:
  - src: '../ansible.cfg'
    dest: configs

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend_base:
    - RUN $PYCMD -m ensurepip --upgrade
    - RUN $PYCMD -m pip install --upgrade pip setuptools
  # append: |
  #   LABEL quay.expires-after="45d"