# This is a basic workflow to help you get started with Actions

name: EE Build

# Controls when the workflow will run
on:
  # This is a reusable workflow
  workflow_call:
    inputs:
      EE_FOLDER_NAME:
        description: 'name of the folder where the EE is located (will become the name of the EE)'
        default: ''
        required: true
        type: string
      EE_IMAGE_TAG:
        description: 'just one tag for image build'
        default: 'latest'
        required: true
        type: string
      REGISTRY_NAMESPACE:
        description: 'this is used during the image push to DockerHub'
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        description: 'needed for registry login'
        required: false
      DOCKER_USERNAME:
        description: 'needed for registry login'
        required: false

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: deploy
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install python requirements (ansible-builder)
        run: pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        id: build-image
        working-directory: ${{ inputs.EE_FOLDER_NAME }}
        run: |
          ansible-builder build \
          --tag=${{ inputs.EE_FOLDER_NAME }}:${{ inputs.EE_IMAGE_TAG }} \
          --tag=${{ inputs.EE_FOLDER_NAME }}:${{ github.sha }}

      - name: Push To DockerHub
        id: push-to-dockerhub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ inputs.EE_FOLDER_NAME }}
          tags: |
            ${{ inputs.EE_IMAGE_TAG }}
            ${{ github.sha }}
          registry: docker.io/${{ inputs.REGISTRY_NAMESPACE }}/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 