# Workflow name
name: NetApp EE build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'netapp-ee/**'

  # Schedule workflow run at 00:00 on Sunday
  # schedule:
  #   - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  joshedmonds/ansible-ee-builds/.github/workflows/deploy.yml@main
    with:
      EE_FOLDER_NAME: 'iaas-ee'
      EE_IMAGE_TAG: 'latest'
      REGISTRY_NAMESPACE: 'joshedmonds'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}